services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
      args:
        ENV_FILE: ".env.server"
    container_name: server
    depends_on:
      - postgres-db
      - cache-server-redis
    volumes:
      - ./server/upload:/server/upload
      - ./server/src:/server/src
      - .env.server:/server/.env
    networks:
      - tfd-prod-network
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
      args:
        ENV_FILE: ".env.client"
    container_name: client
    depends_on:
      - server
    volumes:
      - .env.client:/app/.env
    networks:
      - tfd-prod-network
  admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
      args:
        ENV_FILE: ".env.client"
    container_name: admin
    depends_on:
      - server
    volumes:
      - .env.admin:/app/.env
    networks:
      - tfd-prod-network
  nginx-load-balancer:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx-load-balancer
    depends_on:
      - server
    environment:
      - NGINX_SERVER_NAME=localhost
      - HOST_1=server
      # - HOST_2=tfd-elearning-platform-server-2
      # - HOST_3=tfd-elearning-platform-server-3
      - PORT=3000
      - NGINX_MAX_BODY=100M
    networks:
      - tfd-prod-network
  postgres-db:
    image: postgres:14.12
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - tfdb:/var/lib/postgresql/data
    networks:
      - tfd-prod-network
  cache-server-redis:
    image: redis:5
    container_name: cache-server-redis
    networks:
      - tfd-prod-network
volumes:
  tfdb:
networks:
  tfd-prod-network:
    external: true
